language: python
python:
  - "3.6"
  - "3.7"
install:
  - pip install -r requirements.txt
  - pip install codecov
env:
  - SH=bash
  - export PYTHONPATH=$PYTHONPATH:$(pwd)
script:
  - python -m pytest
branches:
  only:
   - master
