language: python
python:
  - "3.6"
  - "3.7"
install:
  - pip install -r requirements.txt
  - pip install codecov
env:
  - SH=bash
  - CURRENT_DIR=$(pwd)
  - TEST_DIR="$CURRENT_DIR/test"
  - export PYTHONPATH=$PYTHONPATH:$(pwd)
script:
  - cd $TEST_DIR && python -m pytest
branches:
  only:
   - master
   