language: python
python:
  - "3.6"
  - "3.7"
install:
  - pip install -r requirements.txt
  - pip install codecov
env:
  - SH=bash
  - export PYTHONPATH=$PYTHONPATH:$(pwd)
before_script:
  - mongo admin --eval 'db.createUser({user:"run_user_run",pwd:"run_pass_run",roles:["dbAdminAnyDatabase"]});'
services:
  - mongodb
script:
  - python -m pytest
branches:
  only:
   - master
